### ISSUE TITLE
Use https://pypi.org/project/truststore/

### ISSUE THREAD

**Issue by kariharju** [Sema4AI/vscode-extension#35]
<a href="https://github.com/fabioz"><img src="https://avatars.githubusercontent.com/u/117621?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [fabioz](https://github.com/fabioz)**
_Wednesday Sep 13, 2023 at 10:48 GMT_
_Originally opened as https://github.com/robocorp/robotframework-lsp/issues/977_

----

Using https://pypi.org/project/truststore/ should enable users with mitm proxy to access conda forge.

**Comment by kariharju** [comment]
<a href="https://github.com/kariharju"><img src="https://avatars.githubusercontent.com/u/56814402?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kariharju](https://github.com/kariharju)**
_Wednesday Sep 13, 2023 at 12:51 GMT_

----

With rcc the following dependency level enables this:
```YAML
channels:
  - conda-forge

dependencies:
  - python=3.10.12
  - truststore=0.8.0
  - pip=23.2.1
  - pip:
    - --use-feature=truststore
    - rpaframework==27.0.1
    - robocorp==1.0.0
```
